
Retention ::==>>

Contact ::==>

SELECT COUNT(*) FROM NRMA_DATA_RETENTION_PROD_TAB;

SELECT COUNT(*) FROM NRMA_DATA_MASKING_PROP_TAB;


SELECT count(DISTINCT CON.ROW_ID)
FROM  SIEBEL.S_CONTACT CON, SIEBEL.S_USER SU WHERE CON.ROW_ID=SU.ROW_ID or CON.EMP_FLG='Y';
 -- 6737
SELECT COUNT(*)
FROM  SIEBEL.S_ORG_EXT WHERE INT_ORG_FLG ='Y'; --32
	
SELECT COUNT(*) FROM SIEBEL.S_CONTACT WHERE EMP_FLG='Y'; -- 6819

SELECT COUNT(*) FROM SIEBEL.S_CONTACT CON, SIEBEL.S_USER SU WHERE CON.ROW_ID=SU.ROW_ID;  6821

SELECT COUNT(*) FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_ORG_EXT';
SELECT COUNT(*) FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT';

SELECT COUNT(*) FROM SIEBEL.S_CONTACT;
SELECT COUNT(distinct t.contact_id) FROM NRMA_DATA_RETENTION_TAB;

SELECT COUNT(*) FROM NRMA_DATA_RETENTION_TAB;


Base_table_prod_count :==>>

SELECT TO_CHAR(A.CREATED,'YYYY') AS YEAR,X.ATTRIB_18 AS TENURE, COUNT(*)
  FROM SIEBEL.S_ASSET A,SIEBEL.S_CONTACT C,SIEBEL.S_CONTACT_X X, SIEBEL.S_PROD_INT P
WHERE A.OWNER_CON_ID = C.ROW_ID AND C.ROW_ID = X.PAR_ROW_ID(+)
AND A.PROD_ID = P.ROW_ID AND P.PART_NUM=V_PART_NUM
AND A.CREATED>=V_START_DATE
AND A.CREATED<=V_END_DATE
GROUP BY TO_CHAR(A.CREATED,'YYYY'),X.ATTRIB_18;


SELECT P.PART_NUM,COUNT(distinct c.row_id) FROM SIEBEL.S_ASSET A,SIEBEL.S_CONTACT C,siebel.s_prod_int p,SIEBEL.S_CONTACT_X X
WHERE A.OWNER_CON_ID = C.par_ROW_ID AND A.PROD_ID=p.ROW_ID AND c.row_id = X.PAR_ROW_ID(+)
GROUP BY P.PART_NUM;

Retention_table_prod_count :==>>

SELECT P.PART_NUM,COUNT(distinct t.contact_id)FROM SIEBEL.S_ASSET A,nrma_data_retention_tab t,siebel.s_prod_int p,SIEBEL.S_CONTACT_X X
WHERE A.OWNER_CON_ID = t.contact_id AND A.PROD_ID=p.ROW_ID  AND t.contact_id = X.PAR_ROW_ID(+) 
GROUP BY P.PART_NUM;


SELECT P.PART_NUM,COUNT(distinct t.contact_id) FROM SIEBEL.S_ASSET A,nrma_data_retention_tab t,siebel.s_prod_int p,SIEBEL.S_CONTACT_X X
WHERE A.OWNER_CON_ID = t.contact_id AND A.PROD_ID=p.ROW_ID AND P.PART_NUM='ADV' AND t.contact_id = X.PAR_ROW_ID(+) 
GROUP BY P.PART_NUM; --200

SELECT P.PART_NUM,COUNT(distinct c.row_id) FROM SIEBEL.S_ASSET A,SIEBEL.S_CONTACT C,siebel.s_prod_int p,SIEBEL.S_CONTACT_X X
WHERE A.OWNER_CON_ID = C.par_ROW_ID AND A.PROD_ID=p.ROW_ID  AND P.PART_NUM='ADV' AND c.row_id = X.PAR_ROW_ID(+)
GROUP BY P.PART_NUM; -- 20

==================================================================

Retention for Account :==>

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ORG_EXT T1, SIEBEL.S_PARTY_PER T2
WHERE  T1.ROW_ID = T2.PARTY_ID AND (T2.PERSON_ID IN (SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB) OR
T2.PERSON_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT COUNT(*) FROM NRMA_ACCOUNT_DATA_RETENTION;

SELECT COUNT(distinct ACCNT_ID) FROM NRMA_ACCOUNT_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_ORG_EXT;
====================================================================

Retention for ORDER :==>

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ORDER T1 WHERE T1.ACCNT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);


SELECT DISTINCT ROW_ID  FROM SIEBEL.S_ORDER WHERE CONTACT_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB ) OR
CONTACT_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT COUNT(*) FROM NRMA_ORDER_DATA_RETENTION; 

SELECT COUNT(distinct ORDER_ID) FROM NRMA_ORDER_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_ORDER;

================================================================================== 

Retention for ADDR_PER :==>

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ADDR_PER T1,SIEBEL.S_CON_ADDR T2
WHERE T1.ROW_ID=T2.ADDR_PER_ID AND (T2.CONTACT_ID IN (SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB) OR
T2.CONTACT_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT'));

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ADDR_PER T1,SIEBEL.S_CON_ADDR T2
WHERE T1.ROW_ID=T2.ADDR_PER_ID AND T2.ACCNT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);

SELECT COUNT(*) FROM NRMA_ADDR_PER_DATA_RETENTION;

SELECT COUNT(distinct ADDR_PER_ID) FROM NRMA_ADDR_PER_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_ADDR_PER;

======================================================================================

Retention for Agreement :==>

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_DOC_AGREE T1
WHERE T1.TARGET_OU_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION;

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_DOC_AGREE T1, SIEBEL.S_ACCNT_AGR_CUT T2
WHERE T1.ROW_ID = T2.AGREE_ID AND T2.ACCNT_ID IS NOT NULL AND T2.ACCNT_ID NOT LIKE 'NO%'
AND T2.ACCNT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);

SELECT COUNT(*) FROM NRMA_AGREE_DATA_RETENTION;

SELECT COUNT(distinct AGREEMENT_ID) FROM NRMA_AGREE_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_DOC_AGREE;

=====================================================================

Retention for Asset :==>

SELECT DISTINCT ROW_ID FROM SIEBEL.S_ASSET WHERE OWNER_CON_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB ) OR
OWNER_CON_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ASSET T1 WHERE T1.OWNER_ACCNT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);


SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_ASSET T1 WHERE 
T1.SERV_ACCT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);

SELECT DISTINCT ROW_ID FROM SIEBEL.S_ASSET WHERE ORIG_ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM NRMA_ORDER_DATA_RETENTION);

SELECT COUNT(*)  FROM NRMA_ASSET_DATA_RETENTION;

SELECT COUNT(distinct ASSET_ID) FROM NRMA_ASSET_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_ASSET;

=====================================================================

Retention for DOC_QUOTE :==>

SELECT DISTINCT ROW_ID FROM SIEBEL.S_DOC_QUOTE WHERE CON_PER_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB )
OR CON_PER_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_DOC_QUOTE T1 WHERE T1.TARGET_OU_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);

SELECT COUNT(*) FROM NRMA_DOC_QUOTE_DATA_RETENTION;

SELECT COUNT(distinct DOC_QUOTE_ID) FROM NRMA_DOC_QUOTE_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_DOC_QUOTE;
====================================================================

Retention for EVT_ACT :==>
 
SELECT DISTINCT ROW_ID FROM SIEBEL.S_EVT_ACT WHERE TARGET_PER_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB )
OR TARGET_PER_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_EVT_ACT T1 WHERE T1.TARGET_OU_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);


SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_EVT_ACT T1 WHERE
T1.target_per_addr_id IN (SELECT DISTINCT ADDR_PER_ID FROM nrma_addr_per_data_retention);

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_EVT_ACT T1 WHERE
T1.order_item_id IN (SELECT ROW_ID FROM SIEBEL.S_ORDER_ITEM ORD
WHERE ORD.ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM NRMA_ORDER_DATA_RETENTION))

SELECT COUNT(*) FROM nrma_evtact_data_retention; 

SELECT COUNT(distinct ACT_ID) FROM nrma_evtact_data_retention;

SELECT COUNT(*) FROM SIEBEL.S_EVT_ACT;



=====================================================================================

Retention for SRC_PAYMENT :==>

SELECT DISTINCT ROW_ID FROM SIEBEL.S_SRC_PAYMENT WHERE CON_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB )
OR CON_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_SRC_PAYMENT T1 WHERE T1.ACCNT_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION);


SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_SRC_PAYMENT T1 WHERE
T1.ORDER_ID IN (SELECT ORDER_ID FROM NRMA_ORDER_DATA_RETENTION);

SELECT COUNT(*) FROM NRMA_SRCPAY_DATA_RETENTION; 

SELECT COUNT(distinct SRCPAY_ID) FROM NRMA_SRCPAY_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_SRC_PAYMENT;



==========================================================================================


Retention for SR :==>

SELECT DISTINCT ROW_ID FROM SIEBEL.S_SRV_REQ WHERE CST_CON_ID IN ( SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB )
OR CST_CON_ID IN (SELECT OBJ_ID FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT');


SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_SRV_REQ T1 WHERE T1.CST_OU_ID IN (SELECT DISTINCT ACCNT_ID FROM NRMA_ACCOUNT_DATA_RETENTION)

SELECT DISTINCT T1.ROW_ID FROM SIEBEL.S_SRV_REQ T1,NRMA_ASSET_DATA_RETENTION T2 WHERE T1.ASSET_ID = T2.ASSET_ID

SELECT COUNT(*) FROM NRMA_SRV_REQ_DATA_RETENTION;

SELECT COUNT(distinct SR_ID) FROM NRMA_SRV_REQ_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_SRV_REQ;

=================================================================





SELECT COUNT(DISTINCT ROW_ID) FROM SIEBEL.S_ORDER_ITEM WHERE ORDER_ID NOT IN (SELECT ORDER_ID FROM NRMA_ORDER_DATA_RETENTION);




SELECT COUNT(*) FROM SIEBEL.S_ORDER_ITEM;


==================================================================

PRUNING ::==>

SELECT COUNT(*) FROM SIEBEL.S_DOC_QUOTE;
SELECT COUNT(*) FROM NRMA_DOC_QUOTE_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_SRC_PAYMENT;
SELECT COUNT(*) FROM NRMA_SRCPAY_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_DOC_AGREE;
SELECT COUNT(*) FROM NRMA_AGREE_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_SRV_REQ;
SELECT COUNT(*) FROM NRMA_SRV_REQ_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_EVT_ACT;
SELECT COUNT(*) FROM nrma_evtact_data_retention; 

SELECT COUNT(*) FROM SIEBEL.S_ASSET;
SELECT COUNT(*)  FROM NRMA_ASSET_DATA_RETENTION;

SELECT COUNT(*) FROM SIEBEL.S_ORDER_ITEM;
SELECT COUNT(*) FROM  SIEBEL.S_ORDER_ITEM WHERE ORDER_ID IN (SELECT DISTINCT ORDER_ID FROM NRMA_ORDER_DATA_RETENTION)

SELECT COUNT(*) FROM SIEBEL.S_ORDER;
SELECT COUNT(*) FROM NRMA_ORDER_DATA_RETENTION; 

SELECT COUNT(*) FROM NRMA_ADDR_PER_DATA_RETENTION;
SELECT COUNT(*) FROM SIEBEL.S_ADDR_PER;


SELECT COUNT(*) FROM SIEBEL.S_ORG_EXT;
SELECT COUNT(*) FROM NRMA_ACCOUNT_DATA_RETENTION;
SELECT COUNT(*) FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_ORG_EXT';

SELECT COUNT(*) FROM SIEBEL.S_CONTACT;
SELECT COUNT(*) FROM NRMA_DATA_RETENTION_SYS_TAB WHERE OBJ_NAME='S_CONTACT';
SELECT CONTACT_ID FROM NRMA_DATA_RETENTION_TAB;

SELECT COUNT(*) FROM NRMA_DATA_RETENTION_TAB;











